### ISSUE TITLE
there is no clients.txt

### ISSUE THREAD

**Issue by suijunqiang** [RIKSOF/node-wifidog-auth#2]
the file can not be found when node server.js
I have tried to touch a empty clients.txt file, but node throw exceptions of JSON
so would you please help me to run your project?

thanks & Best regards

error message:

_info: Listening on port 8081 with SSL false
undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /home/sui/src/node/node-wifidog-auth/models/Clients.js:204:27
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)_

**Comment by suijunqiang** [comment]
It works after putting any json strings into clients.txt, I am not sure if it any other runtime issus;

BYW

anyone know how to set wifidog.conf to connect this auth server? such as login.php...

GatewayID default
#GatewayInterface bridge0
GatewayInterface rmnet_ipa0
GatewayAddress 192.168.1.1  

AuthServer {
    #Hostname http://192.168.1.118
    Hostname www.suijunqiang.win
    #Hostname http://101.132.37.52
    #Hostname  http://www.skybureau.cn/kevin/
    SSLAvailable no
    HTTPPort 8081
    #HTTPPort 8081
    #HTTPPort 3001
    Path /wifidog/
    LoginScriptPathFragment login.php? 
    PortalScriptPathFragment portal.php?
    MsgScriptPathFragment message.php?
    PingScriptPathFragment ping.php?
    AuthScriptPathFragment auth.php?
}

GatewayPort 2060  

CheckInterval 60  
ClientTimeout 5 
ClientTimeout

TrustedMACList 18:87:40:af:2a:56,00:00:DE:AD:BE:AF,00:00:C0:1D:F0:0D 

Thanks & Best Regards
Sui
